Repository TUK-PETSTORY/frontend, pull requests merged in 2024-07, with the labels that each got.

#2 Publishing/1 AppBar, TapBar, NavBar 퍼블리싱
  assets/fonts/mainfont.ttf
  lib/src/app.dart
  lib/src/screens/boast.dart
  lib/src/screens/home.dart
  lib/src/screens/intro.dart
  pubspec.yaml
Labels: publishing

#6 Publishing/5 추천사이트
  lib/src/app.dart
  lib/src/screens/home.dart
  lib/src/screens/shop/index.dart
  lib/src/screens/shop/show.dart
Labels: publishing

#4 Publishing/3 자식자랑 페이지 퍼블리싱
  lib/src/feed/feed_listitem.dart
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunityMain.dart
  lib/src/screens/home.dart
Labels: publishing

#8 Publishing/7 육아꿀팁 페이지 퍼블리싱
  lib/src/app.dart
  lib/src/feed/feed_listitem.dart
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunity/childcare_tips.dart
  lib/src/screens/comunityMain.dart
Labels: publishing

#10 Publishing/9 입양페이지 퍼블리싱
  lib/src/feed/petconnection_list.dart
  lib/src/screens/comunity/petConnection.dart
  lib/src/screens/comunityMain.dart
Labels: publishing

#13 [refactor] 재사용을 위한 모듈화 및 패키지 정리
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunity/childcare_tips.dart
  lib/src/screens/comunity/petConnection.dart
  lib/src/screens/shop/index.dart
  lib/src/screens/shop/show.dart
  lib/widgets/listitems/feed_list_item.dart
  lib/widgets/listitems/petconnection_list_item.dart
  lib/widgets/listitems/site_list_item.dart
  pubspec.yaml
Labels: refactor

#14 Publishing/11 글작성, 수정페이지 퍼블리싱
  android/app/src/main/AndroidManifest.xml
  lib/src/screens/imagepicker.dart
  lib/src/screens/postedit.dart
  pubspec.yaml
Labels: publishing

#19 Publishing/18 모달 퍼블리싱
  lib/widgets/listitems/feed_list_item.dart
Labels: publishing

#21 [publishing] 마이페이지 퍼블리싱
  lib/src/screens/home.dart
  lib/src/screens/mypage/index.dart
  lib/src/screens/mypage/show.dart
  lib/widgets/listitems/my_post_list_item.dart
Labels: publishing

#22 [publishing] 로그인/회원가입 연동
  lib/src/controllers/auth_controller.dart
  lib/src/providers/auth_provider.dart
  lib/src/providers/provider.dart
  lib/src/screens/intro.dart
  lib/src/screens/signup.dart
  lib/src/shared/Global.dart
Labels: publishing

#25 Feat/23 게시글 조회 연동
  lib/main.dart
  lib/src/controllers/auth_controller.dart
  lib/src/controllers/post_controller.dart
  lib/src/providers/post_provider.dart
  lib/src/providers/provider.dart
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunity/childcare_tips.dart
  lib/src/shared/Global.dart
  lib/widgets/listitems/feed_list_item.dart
  pubspec.yaml
Labels: publishing

#27 [feat] 추천사이트와 마이페이지 연동
  lib/src/controllers/auth_controller.dart
  lib/src/controllers/like_controller.dart
  lib/src/controllers/site_controller.dart
  lib/src/providers/auth_provider.dart
  lib/src/providers/like_provider.dart
  lib/src/providers/provider.dart
  lib/src/providers/site_provider.dart
  lib/src/screens/home.dart
  lib/src/screens/intro.dart
  lib/src/screens/mypage/index.dart
  lib/src/screens/mypage/show.dart
  lib/src/screens/shop/show.dart
  lib/src/screens/site/index.dart
  lib/src/screens/site/show.dart
  lib/src/shared/Global.dart
  lib/widgets/listitems/my_post_list_item.dart
  lib/widgets/listitems/site_list_item.dart
Labels: feat

#32 [feat] 게시글 삭제
  lib/src/controllers/post_controller.dart
  lib/widgets/listitems/feed_list_item.dart
Labels: feat

#34 33 feat 게시글 작성 연동
  lib/src/controllers/post_controller.dart
  lib/src/providers/post_provider.dart
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunity/childcare_tips.dart
  lib/src/screens/postedit.dart
  lib/widgets/listitems/feed_list_item.dart
Labels: feat

#39 [feat] 육아 꿀팁 조회 연동 완료
  lib/src/controllers/post_controller.dart
  lib/src/screens/comunity/childBoast.dart
  lib/src/screens/comunity/childcare_tips.dart
  lib/src/screens/comunity/pet_connection.dart
  lib/src/screens/comunityMain.dart
  lib/src/screens/site/favorite.dart
  lib/src/screens/site/show.dart
  lib/widgets/listitems/site_list_item.dart
Labels: feat
